### PR TITLE
Build with Travis

### PR DESCRIPTION
**Pull request by alxndrsn**
This should build the project with travis.  It won't currently upload APKs, but once this is done for `medic-android` it can be done for this project too.

To facilitate building on travis, the project has been converted to use `gradle` for building.  This may not be very convenient - please let me know!

Also, the javarosa JAR is included in this repo.  Ideally this would be versioned, and fetched from a remote repo.  The same goes for the JARs in `lib/`, although some of them - notably `google-play-services.jar` - do not seem to be publicly available.

### CODE REVIEW

**Comment by alxndrsn** [comment]
Probably, yes.  This hadn't occurred to me.  I will see how easy it is to configure their locations with gradle.

**Comment by abbyad** [comment]
Looks better, thanks!

**Comment by abbyad** [comment]
Just want to confirm that the project can still be built using Eclipse.

To do so you may need to uncheck `javarosa-core` from the *medic-collect > Properties > Java Build Path*:

image

Otherwise I was getting this build error:
```
[2015-07-03 14:57:14 - Dex Loader] Unable to execute dex: Multiple dex files define Lorg/javarosa/core/api/Constants;
[2015-07-03 14:57:14 - medic-collect] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lorg/javarosa/core/api/Constants;
```

**Comment by alxndrsn** [comment]
Great!  If you want to edit javarosa-core in Eclipse though, you'll want to re-add that project and exclude `libs/javarosa-libraries.jar`

**Pull request merged**
