### PR TITLE
Update travis to test, build, and publish commits with tags

### LINKED ISSUE #17: Allow specifying password per flavor/build
Currently the password is set as part of the Global Credentials, which means all APKs in a build have the same password. Once #16 is complete individual project builds can be done so APKs will unlikely have the wrong password, but it does still mean that the password would need to be set separately. It would be simpler to set the password per flavor, or set it as a build parameter.

### PR DESCRIPTION
**Pull request by kennsippell**
#27 

* Travis runs unit tests for all builds
* Travis performs a debug build of all flavors and publishes to GitHub. [Example v1.4.6](https://github.com/medic/medic-collect/releases/tag/v1.4.6)
* This build is agnostic of ABI, so no need for x64 builds.
* As discussed, not publishing to app store.
* Fixes #17. You can set the password in https://travis-ci.org/medic/medic-collect/settings

Still needing the following information from @abbyad:

* Can you confirm you typically build and release debug builds to users? Can you confirm we should continue to do this moving forward for continuity?
* Would you be willing to update the passwords for each flavor in https://travis-ci.org/medic/medic-collect/settings and let me know when it is ready for a re-build?
* I need to know which flavors set `BIKRAM_SAMBAT: true`

### CODE REVIEW

**Comment by kennsippell** [comment]
Waiting on @jillrshah to compile the above information, but I think we can proceed with code review for this.

**Comment by kennsippell** [comment]
Waiting on @jillrshah to compile the above information, but I think we can proceed with code review for this.

**Review by garethbowen — APPROVED** [review]
Awesome.

**Comment by kennsippell** [comment]
> Can you confirm you typically build and release debug builds to users? Can you confirm we should continue to do this moving forward for continuity?

I've moved this conversation to #30. Fix can be prioritised as necessary.

> Would you be willing to update the passwords for each flavor in https://travis-ci.org/medic/medic-collect/settings and let me know when it is ready for a re-build?

We can do this post-merge.

> I need to know which flavors set BIKRAM_SAMBAT: true

Sounds like the only flavor for this is `safesimbaglung`. I've opened #31 because that flavor isn't in the repo.

**Pull request merged**
